export const allConsoles = [
  {
    id: "gta",
    title: "GTA Edition",
    genre: "game-themed",
    displayGenre: "Console Design",
    price: "$499.99",
    image: "images/consoles/gta console.jpeg",
    description:
      "Live the high-speed chaos of Los Santos on this GTA-inspired console.",
    type: "console",
  },
  {
    id: "spiderhero",
    title: "Spider Hero",
    genre: "controller custom",
    displayGenre: "Controller Design",
    price: "$69.99",
    image: "images/controllers/spider controller.jpeg",
    description: "Webbed with red and black, heroic and stylish.",
    type: "controller",
  },
  {
    id: "default",
    title: "Default",
    genre: "controller standard",
    displayGenre: "Controller Design",
    price: "$59.99",
    image: "images/controllers/default controller.jpeg",
    description: "Clean, minimal, and classic DualSense style.",
    type: "controller",
  },
  {
    id: "blue-flame",
    title: "Blue Flame",
    genre: "elemental",
    displayGenre: "Console Design",
    price: "$499.99",
    image: "images/consoles/blue flame console.jpeg",
    description:
      "Fiery energy meets cool blue visuals for an electric gaming experience.",
    type: "console",
  },
  {
    id: "balan-wonderworld",
    title: "Balan Wonderworld",
    genre: "game-themed",
    displayGenre: "Console Design",
    price: "$499.99",
    image: "images/consoles/balan wonderworld console.jpeg",
    description: "Whimsical and vibrant design inspired by Balan Wonderworld.",
    type: "console",
  },
  {
    id: "joker",
    title: "Joker",
    genre: "comic-book",
    displayGenre: "Console Design",
    price: "$499.99",
    image: "images/consoles/joker console.jpeg",
    description:
      "Play with chaos in this Joker-inspired purple and green design.",
    type: "console",
  },
  {
    id: "crimsonshadow",
    title: "Crimson Shadow",
    genre: "controller colorway",
    displayGenre: "Controller Design",
    price: "$64.99",
    image: "images/controllers/red-black controller.jpeg",
    description: "Striking red over a black base for a bold contrast.",
    type: "controller",
  },
  {
    id: "gold-console",
    title: "Gold Edition",
    genre: "luxury",
    displayGenre: "Console Design",
    price: "$599.99",
    image: "images/consoles/gold console.jpeg",
    description:
      "A stunning design with bold gold plating and a premium shine.",
    type: "console",
  },
  {
    id: "spider-man",
    title: "Spider-Man",
    genre: "superhero",
    displayGenre: "Console Design",
    price: "$499.99",
    image: "images/consoles/spider-man console.jpeg",
    description: "Classic Spider-Man red webbing over black armor.",
    type: "console",
  },
  {
    id: "chelsea",
    title: "Chelsea",
    genre: "football-themed",
    displayGenre: "Console Design",
    price: "$499.99",
    image: "images/consoles/chelsea console.jpeg",
    description: "A blue beauty dedicated to loyal Chelsea supporters.",
    type: "console",
  },
  {
    id: "uefa",
    title: "UEFA Edition",
    genre: "controller sports",
    displayGenre: "Controller Design",
    price: "$69.99",
    image: "images/controllers/uefa champions league controller.jpeg",
    description: "Football fever meets immersive gaming action.",
    type: "controller",
  },
  {
    id: "default",
    title: "Default PS5",
    genre: "standard",
    displayGenre: "Console Design",
    price: "$499.99",
    image: "images/consoles/default console.jpeg",
    description:
      "The official sleek and futuristic design of the original PS5 console.",
    type: "console",
  },
  {
    id: "bloodpaint",
    title: "Blood Paint",
    genre: "controller limited-edition",
    displayGenre: "Controller Design",
    price: "$69.99",
    image: "images/controllers/blood paint controller.jpeg",
    description: "A gritty, battle-worn design for fearless gamers.",
    type: "controller",
  },
  {
    id: "blue-marble",
    title: "Blue Marble",
    genre: "nature-inspired",
    displayGenre: "Console Design",
    price: "$499.99",
    image: "images/consoles/blue marble console.jpeg",
    description: "Marble-inspired swirls of blue bring style and serenity.",
    type: "console",
  },
  {
    id: "abyss-blue",
    title: "Abyss Blue",
    genre: "sci-fi",
    displayGenre: "Console Design",
    price: "$499.99",
    image: "images/consoles/blue stone console.jpeg",
    description: "Dive into deep blue darkness with this sleek design.",
    type: "console",
  },
  {
    id: "miles",
    title: "Miles Morales",
    genre: "superhero",
    displayGenre: "Console Design",
    price: "$499.99",
    image: "images/consoles/miles console.jpeg",
    description: "Bold red and black combo inspired by Miles Morales' style.",
    type: "console",
  },
  {
    id: "deathstroke",
    title: "Deathstroke",
    genre: "comic-book",
    displayGenre: "Console Design",
    price: "$499.99",
    image: "images/consoles/deathstroke console.jpeg",
    description:
      "Dark, menacing orange and black armor inspired by the mercenary Deathstroke.",
    type: "console",
  },
  {
    id: "arsenal",
    title: "Arsenal",
    genre: "football-themed",
    displayGenre: "Console Design",
    price: "$499.99",
    image: "images/consoles/arsenal console.jpeg",
    description: "A bold red Arsenal-themed console for die-hard Gunners fans.",
    type: "console",
  },
  {
    id: "black-hole",
    title: "Black Hole",
    genre: "sci-fi",
    displayGenre: "Console Design",
    price: "$499.99",
    image: "images/consoles/black hole console.jpeg",
    description: "Deep space inspiration with a mysterious cosmic vibe.",
    type: "console",
  },
  {
    id: "on-fire",
    title: "On Fire",
    genre: "elemental",
    displayGenre: "Console Design",
    price: "$499.99",
    image: "images/consoles/on fire console.jpeg",
    description: "This console is literally flaming with style and power.",
    type: "console",
  },
  {
    id: "stealthsoldier",
    title: "Stealth Soldier",
    genre: "controller camo",
    displayGenre: "Controller Design",
    price: "$64.99",
    image: "images/controllers/stealth soldier.jpeg",
    description: "Tactical and rugged for intense gameplay.",
    type: "controller",
  },
  {
    id: "blue-red-flame",
    title: "Blue Red Flame",
    genre: "elemental",
    displayGenre: "Console Design",
    price: "$499.99",
    image: "images/consoles/golden 1 console.jpeg",
    description: "Dynamic fire design with vivid red and blue flames.",
    type: "console",
  },
  {
    id: "gradientblue",
    title: "Gradient Blue",
    genre: "controller colorway",
    displayGenre: "Controller Design",
    price: "$64.99",
    image: "images/controllers/gradient blue controller.jpeg",
    description: "Smooth blue tones for a calm gaming flow.",
    type: "controller",
  },
  {
    id: "red-marble",
    title: "Red Marble",
    genre: "nature-inspired",
    displayGenre: "Console Design",
    price: "$499.99",
    image: "images/consoles/red marble console.jpeg",
    description: "Elegant swirls of red marble for a premium look.",
    type: "console",
  },
  {
    id: "assassin-creed",
    title: "Assassin's Creed",
    genre: "game-themed",
    displayGenre: "Console Design",
    price: "$499.99",
    image: "images/consoles/assassin creed console.jpeg",
    description:
      "Stealth and elegance come alive with this Assassin’s Creed design.",
    type: "console",
  },
  {
    id: "morals",
    title: "Spider-Man Morals",
    genre: "superhero",
    displayGenre: "Console Design",
    price: "$499.99",
    image: "images/consoles/morals console.jpeg",
    description: "Heroic energy from Spider-Man’s legacy in a dark aesthetic.",
    type: "console",
  },
  {
    id: "son-goku",
    title: "Son Goku",
    genre: "anime",
    displayGenre: "Console Design",
    price: "$499.99",
    image: "images/consoles/son goku console.jpeg",
    description:
      "Saiyan power unleashed with this vibrant Dragon Ball Goku design.",
    type: "console",
  },
  {
    id: "default2",
    title: "Default 2",
    genre: "controller standard",
    displayGenre: "Controller Design",
    price: "$59.99",
    image: "images/controllers/default 2 controller.jpeg",
    description: "A refined, futuristic default with a twist.",
    type: "controller",
  },
  {
    id: "blue-carbon",
    title: "Blue Carbon Skin",
    genre: "tech-style",
    displayGenre: "Console Design",
    price: "$499.99",
    image: "images/consoles/blue carbon skin console.jpeg",
    description: "Futuristic carbon-fiber aesthetic in icy blue tones.",
    type: "console",
  },
  {
    id: "stars",
    title: "Stars Edition",
    genre: "sci-fi",
    displayGenre: "Console Design",
    price: "$499.99",
    image: "images/consoles/stars console.jpeg",
    description: "A galactic theme perfect for stargazers and dreamers.",
    type: "console",
  },
  {
    id: "golden",
    title: "Golden Gloss",
    genre: "luxury",
    displayGenre: "Console Design",
    price: "$599.99",
    image: "images/consoles/golden console.jpeg",
    description: "Pure golden brilliance for those who like to game in style.",
    type: "console",
  },
  {
    id: "gold-blade",
    title: "Gold Blade",
    genre: "luxury",
    displayGenre: "Console Design",
    price: "$499.99",
    image: "images/consoles/hero 2.jpeg",
    description: "Sleek golden console with a sharp, elite look.",
    type: "console",
  },
  {
    id: "spidermanedition",
    title: "Spider-Man Edition",
    genre: "controller exclusive",
    displayGenre: "Controller Design",
    price: "$74.99",
    image: "images/controllers/spider man controller.jpeg",
    description: "Officially themed for Marvel fans and true believers.",
    type: "controller",
  },
  {
    id: "console-covers",
    title: "Splitscreen Covers Pack",
    genre: "accessory",
    displayGenre: "Console Design",
    price: "$69.99",
    image: "images/consoles/Console Covers.jpeg",
    description:
      "A premium accessory pack with multiple themed console covers.",
    type: "console",
  },
  {
    id: "dragon",
    title: "Dragon Kombat",
    genre: "game-themed",
    displayGenre: "Console Design",
    price: "$499.99",
    image: "images/consoles/dragon console.jpeg",
    description:
      "Power and myth combined in this Mortal Kombat inspired console skin.",
    type: "console",
  },
  {
    id: "white-black-marble",
    title: "White Black Marble",
    genre: "minimalist",
    displayGenre: "Console Design",
    price: "$499.99",
    image: "images/consoles/white-black marble console.jpeg",
    description:
      "Clean contrast of black and white marble textures for a modern look.",
    type: "console",
  },
  {
    id: "green-glass",
    title: "Green Glass",
    genre: "futuristic",
    displayGenre: "Console Design",
    price: "$499.99",
    image: "images/consoles/green glass console.jpeg",
    description: "Slick emerald finish with a high-tech crystalline look.",
    type: "console",
  },
  {
    id: "skyblue",
    title: "Sky Blue",
    genre: "controller colorway",
    displayGenre: "Controller Design",
    price: "$64.99",
    image: "images/controllers/sky blue controller.jpeg",
    description: "Light and breezy, designed for smooth sessions.",
    type: "controller",
  },
  {
    id: "electricyellow",
    title: "Electric Yellow",
    genre: "controller colorway",
    displayGenre: "Controller Design",
    price: "$64.99",
    image: "images/controllers/yellow controller.jpeg",
    description: "Bright and energetic, for players who stand out.",
    type: "controller",
  },
  {
    id: "bayern",
    title: "Bayern Munich",
    genre: "football-themed",
    displayGenre: "Console Design",
    price: "$499.99",
    image: "images/consoles/bayern console.jpeg",
    description:
      "Celebrate German football greatness with this Bayern edition.",
    type: "console",
  },
  {
    id: "gta",
    title: "GTA Limited",
    genre: "controller limited-edition",
    displayGenre: "Controller Design",
    price: "$69.99",
    image: "images/controllers/gta controller.jpeg",
    description: "A vibrant tribute to the streets of Los Santos.",
    type: "controller",
  },
  {
    id: "brush-drawing",
    title: "Brush Drawing",
    genre: "artistic",
    displayGenre: "Console Design",
    price: "$499.99",
    image: "images/consoles/brush drawing console.jpeg",
    description:
      "Elegant brush-stroke floral art for a touch of tradition and beauty.",
    type: "console",
  },
  {
    id: "grimoire",
    title: "Grimoire",
    genre: "fantasy",
    displayGenre: "Console Design",
    price: "$499.99",
    image: "images/consoles/grimoire console.jpeg",
    description: "Ancient runes and gold details summon a magical style.",
    type: "console",
  },
  {
    id: "silver-carbon",
    title: "Silver Carbon Skin",
    genre: "tech-style",
    displayGenre: "Console Design",
    price: "$499.99",
    image: "images/consoles/silver carbon skin console.jpeg",
    description:
      "High-performance silver carbon finish for a sharp and clean aesthetic.",
    type: "console",
  },
  {
    id: "blue-shine",
    title: "Blue Shine",
    genre: "futuristic",
    displayGenre: "Console Design",
    price: "$499.99",
    image: "images/consoles/hero 1.jpeg",
    description: "High-gloss finish with glowing accents for modern gamers.",
    type: "console",
  },
];
